### ISSUE TITLE
`set_buzzer_active`, `set_led_active` and `set_live_tracking_active` methods don't work

### ISSUE THREAD

**Issue by bieniu** [zhulik/aiotractive#14]
When I try to call these methods (with the parameter `True`), the service returns: 
```
{'active': False, 'started_at': None, 'timeout': 300, 'remaining': 0, 'pending': True}
``` 
 and nothing happens.

**Comment by zhulik** [comment]
Do the functions work from the app? The response with `'pending: True'` seems ok in this case. What events do you receive after you call the function?

**Comment by bieniu** [comment]
Strange, today everything works. Yesterday I tried 2 hours with no success. The service didn't send any event after calling the functions, but app control worked.

**Comment by bieniu** [comment]
We can close the case because I am unable to reproduce the problem.
