### ISSUE TITLE
Activity & Daily Goal Unavailable

### ISSUE THREAD

**Issue by Sergeant-Steve** [zhulik/aiotractive#31]
Tractive changed how they measure activity and sleep on the 26th March 2024, and now Daily Activity and Daily Goal are no longer available in Home Assistant using the official integration which uses this Library.

I presume the API has changed slightly in relation to the changes that they announced by email.

**Comment by bieniu** [comment]
This issue has already been fixed on the HA side https://github.com/home-assistant/core/pull/114380
