### ISSUE TITLE
`aiotractive` 0.6.0 is not available via `pip`

### ISSUE THREAD

**Issue by bieniu** [zhulik/aiotractive#34]
https://pypi.org/project/aiotractive/#history

`Bump version` GH action failed https://github.com/zhulik/aiotractive/actions/runs/9785796276

![obraz](https://github.com/zhulik/aiotractive/assets/478555/21ffbff4-f476-4c5c-a1d2-5899cf8d7508)

**Comment by zhulik** [comment]
I'll look into it today

**Comment by Kokahontas13** [comment]
Can we move this forward? Tractive integration is not workling and waiting for this PR

**Comment by zhulik** [comment]
0.6.0 is now available on Pypi
